// Table for FunctionDefinition
Table infra.haruna_function_definition {
  id integer [pk, increment]
  function_name varchar(191) [unique]
  function_arn varchar(191) [unique]
  payload json
}

// FunctionUrlConfig
Table infra.haruna_function_url {
  id integer [pk, increment]

  // arn:aws:lambda:ap-northeast-1:123456789012:function:ayane-dev-http
  function_arn varchar(191) [unique]

  // https://abcdefghijk.lambda-url.ap-northeast-1.on.aws/
  function_url varchar(191) [unique]

  payload json
}
